### ISSUE TITLE
Clean up 'standard' init

### ISSUE THREAD

**Issue by tacaswell** [soft-matter/pims#156]
Remove `process_func`, `as_gray`, `plugin` from the 'standard' init.

Anything else we want to get rid of?

**Comment by danielballan** [comment]
as_grey is still up for debate. I want to phase it out, but maybe not in
the first round.

**Comment by caspervdw** [comment]
I am in favour of removing `as_grey`, because the transformation multichannel -> grey assumes a certain weighing of separate channels, which is acquisition device dependent. This is something the user should think about. 

We could provide a set of pipeline functions providing a standard as_grey transformation, even with an optional weighing argument.

**Comment by danielballan** [comment]
Great. Tom and I had just come to the same conclusion: a set of built-in pipeline functions will always be more flexible than kwargs, and we only have to implement them once, not per-reader.

**Comment by caspervdw** [comment]
Referencing #250

**Comment by nkeim** [comment]
It looks like this was closed by #250.
