### ISSUE TITLE
Opening Axio Vision .zvi files with Pims.Bioformats

### ISSUE THREAD

**Issue by Microfringe** [soft-matter/pims#287]
[test.zip](https://github.com/soft-matter/pims/files/1707088/test.zip)

Hi! 
My plan was, to open my .zvi files and extract the exposure time and the image for further calculations.

When I tried to open a .zvi file with file=pims.Bioformats(‘test.zvi’), everything seems to work at first:
I can access the metadata and extract the exposure time, which matches with what AxioVison tells me.
But when I tried to access the image via slicing, only index file[0] seems to work and this seems to hand me only the red channel of RGB image.
file.get_frame_2D() or file.get_frame(1) or file.get_frame(0) , (-1), (-2)… give the same result.

So I tried to bundle the axes with file.bundle_axes = ‘cyx’ (or [u'c', u'y', u'x'] and several premutations)
file.frame_shape and file.bundle_axes give me the correct results of (3, 1038, 1392) and ['c', 'y', 'x'] respectively.
But when I now try to access the image via file[0] I get:
 
java.lang.IndexOutOfBoundsExceptionPyRaisable: java.lang.IndexOutOfBoundsException: Index 1 out-of-bounds for length 1

The same goes for file.get_frame(0).
Only file.get_frame_2D() seems to work but gives me again the red channel.

Then I got a little bit desperate and tried to change the file.default_coords['c']=1 , but that didn’t seem to influence the silde I get with file.get_frame_2D().

Could you help me access all color channel with pims?

**Comment by caspervdw** [comment]
@Microfringe  Sorry for the late reply. This seems to be an issue in the underlying `Bioformats` libary. You could download the newest version from [here](http://downloads.openmicroscopy.org/bio-formats/5.8.0/artifacts/loci_tools.jar) and use it to replace the `loci_tools.jar` in the `pims` package directory.

If that does not fix your issues, please compare the values inside `file.sizes` with your expected T, C, Y, and X values. Also it might be useful to check `file.size_series`. Is there a mismatch?

The fact that you get only red channels using `file.get_frame_2D()` is expected. This function exclusively reads 2D frames, and you can select particular coordinates using `file.get_frame_2D(t=4, c=0)`. Otherwise it uses the default values stored in `file.default_coords`.
