### ISSUE TITLE
Value error opening tiff

### ISSUE THREAD

**Issue by jrussell25** [soft-matter/pims#374]
Hi there, ive been getting a value error having to do with datetime when pims looks for metadata in some microscopy images I  have. This could be related to #294 but wasn't obviously the same. Below is the code and [here is a link to the test image](https://github.com/jrussell25/data-sharing/blob/master/Pos001_S001_t21_z4_ch01.tif)

```
import pims
import tifffile as tiff
print(pims.__version__) #0.5
print(tiff.__version__) #2020.10.1

tiff_test = tiff.imread('Pos001_S001_t21_z4_ch01.tif') #Its a phase contrast image of yeast cells

pims_test = pims.open('Pos001_S001_t21_z4_ch01.tif')

im = pims_test.get_frame(0)
```

The last line raises 

`ValueError: invalid literal for int() with base 10: '0:00'`

<details><summary>Command Line Output</summary>
<pre>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-173-3ac3cb358dd8> in <module>
----> 1 im.get_frame(0)

/opt/anaconda3/envs/mpl/lib/python3.8/site-packages/pims/tiff_stack.py in get_frame(self, j)
    119         t = self._tiff[j]
    120         data = t.asarray()
--> 121         return Frame(data, frame_no=j, metadata=self._read_metadata(t))
    122 
    123     def _read_metadata(self, tiff):

/opt/anaconda3/envs/mpl/lib/python3.8/site-packages/pims/tiff_stack.py in _read_metadata(self, tiff)
    150                 md[key] = ''
    151             if key == 'DateTime':
--> 152                 md[key] = _tiff_datetime(md[key])
    153         return md
    154 

/opt/anaconda3/envs/mpl/lib/python3.8/site-packages/pims/tiff_stack.py in _tiff_datetime(dt_str)
     49 def _tiff_datetime(dt_str):
     50     """Convert the DateTime string of TIFF files to a datetime object"""
---> 51     return datetime(year=int(dt_str[0:4]), month=int(dt_str[5:7]),
     52                     day=int(dt_str[8:10]), hour=int(dt_str[11:13]),
     53                     minute=int(dt_str[14:16]), second=int(dt_str[17:19]))

ValueError: invalid literal for int() with base 10: '0:00'
</pre>
</details>

The `pims.open` seem fine and it gets the frame size and pixel type correctly, the problem only occurs when trying to get the data into an array.

Thanks for the help.

**Comment by GenevieveBuckley** [comment]
It seems the "DateTime" tag in your tiff file is `'0:00:00 00:00:00'`, which is unusual. I'm not sure how or why that's being written into your file. I don't think this is related to the other issue you linked to.

The `_tiff_datetime()` function in pims is expecting a string with the format `'YYYY:MMM:DD HH:MM:SS'`. It's failing to parse your datetime string correctly because it's assuming that the first four characters should be the year and is trying to convert that into an integer. The first four characters in your datetime string are `0:00`, so the conversion to integer is failing because there's a colon `:` character in there.

I tried splitting the string up using the colon character as a separator, but then we still run into trouble converting it into a datetime object. Zero is not a valid year, or month, etc. 

A better approach might be to use a try/except block and raise a warning (not an error) if there's a problem with the datetime string.
