### ISSUE TITLE
How can I create a list with the file name order?

### ISSUE THREAD

**Issue by forevertheuni** [soft-matter/pims#47]
How can I create a list with the file name order?
After I create my ImageSequence how can I have a list of the file names with the sorted  order of the loaded files?

Thanks

**Comment by yw5aj** [comment]
+1. Some software save files with names that are not necessarily ordered by the same rule, so the capability to customize orders will be a nice feature to have.

**Comment by danielballan** [comment]
@yw5aj Thanks for the comment. If you want to *customize* on the way in, notice that `ImageSequence` accepts a list like:

```
imgs = pims.ImageSequence(['image3.jpg', 'image1.jpg', 'image2.jpg']) 
```

where, as shown, the order is manually given by you and need not be alphabetically sorted.

If, like the original poster, @forevertheuni, you are willing to accept pims' default ordering and only need to know after the fact what that ordering was, use `img._filepaths`. As discussed we can promote that to an officially-supported part of the API (`img.filepaths`) in a future release.

**Comment by tacaswell** [comment]
I am mixed on promoting `_filepaths` to public API, it seems like a reasonable idea but it creates a difference between multi-page files and many single page files.  Making those two things be indistinguishable from the consumer code is one of goals of PIMS.  If analysis code starts to rely on implementation details of a specific sub-class, then you have injected I/O back into your analysis (as you will need to change your analysis code if you change how you store your images).

**Comment by nkeim** [comment]
We have "extended" attributes for rich formats like CINE and NorPix. Analogously, filenames can be used to encode metadata such as timestamps. I think that "filepaths" or "filenames" should be in this category, and we can let the caller duck-type it.

In my own use of pims, there is one piece of code that extracts the timestamp metadata from the reader object and copies it to a separate data structure; the rest of my code uses "vanilla" pims attributes. I think this is a pattern that pims should support and encourage, since metadata tends to be messy.

On Nov 22, 2016, at 5:32 AM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:


I am mixed on promoting _filepaths to public API, it seems like a reasonable idea but it creates a difference between multi-page files and many single page files. Making those two things be indistinguishable from the consumer code is one of goals of PIMS. If analysis code starts to rely on implementation details of a specific sub-class, then you have injected I/O back into your analysis (as you will need to change your analysis code if you change how you store your images).

**Comment by yw5aj** [comment]
@danielballan Thank you Dan for your response!

I actually tried that, but no matter how I order the files in the list, the resultant frames are still in alphabetical order. I had a code snippet:

```python
import pims

frames = pims.ImageSequence(['mid2.png', 'mid0.png', 'mid1.png'])

frames._filepaths


Out[8]: ['mid0.png', 'mid1.png', 'mid2.png']
```

So I thought that it be nice if I can have a keyword option like `keep_order=True` or such.

**Comment by caspervdw** [comment]
Thanks for reporting back! I think this is actually a bug at line

https://github.com/soft-matter/pims/blob/master/pims/image_sequence.py#L129

I am :+1: on removing the sorting when a list is provided.

**Comment by tacaswell** [comment]
This came in via https://github.com/soft-matter/pims/pull/127 which was to fix #103 (so this is my fault).  Should probably make it optional?  I think it could be done with a kwarg?

**Comment by caspervdw** [comment]
I think a kwarg is not necessary. The desired behaviour is as follows: no sorting if the user provides a list, sorting in all other cases. So just removing the `sorted` would solve the issue

**Comment by caspervdw** [comment]
@yw5aj Sorry to let this sit for so long. I made the PR (#252) to solve this. Thanks for the report!

**Comment by yw5aj** [comment]
@caspervdw Not at all - thank YOU so much for working on such a great package of `pims`!
