### ISSUE TITLE
Wrap bioformats

### ISSUE THREAD

**Issue by danielballan** [soft-matter/pims#80]
[python-bioformats](https://github.com/CellProfiler/python-bioformats/) uses javabridge to start a Java VM and access the Java-based [bioformats](https://github.com/openmicroscopy/bioformats). Making a PIMS subclass for this looks fairly straightforward, but it seems to me there are lot of places where this could break.

**Comment by caspervdw** [comment]
@tacaswell, what do you have exactly on meta-data handling of nd2 images in bioformats?

**Comment by tacaswell** [comment]
@caspervdw This was ~6-7 years ago (?!) and I have not worked with nd2 images since (that version of nikon elements was crashing so often we switched to using metamorph, who's files are just re-named tiffs with a huge xml string dumped into one of the free-form header field).  All of my code related to that either got absorbed into upstream or is buried in matlab code.

**Comment by caspervdw** [comment]
As this is implemented in https://github.com/soft-matter/pims/pull/109 and https://github.com/soft-matter/pims/pull/144, we can close this
